# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02012cdfc07fcaeaaf35a62fc592830bb1caf2dfdf309d7899c6fc3003f7b890734eba1b35f5cbc77411857ef1ac7d3d1d369fdd73faa80ad2c26c5bfff9c6a8

test:
  secret_key_base: fb19bc47e2a91d89a9ab9b2a444fe8cd4ed6d2f73e0102c15c9913de90236c60f0784b27c03aa81897ff0ddc0fd21616d18519a886c2b06a932be80acdc6f007

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
